sudo: required

services:
  - docker

before-insall:
  - docker build -t girishsakhare/docker-react -f Dockerfile.dev .

script:
  - docker run girishsakhare/docker-react npm run test -- --coverage #-- --coverage added to exit after the tests are run
