sudo: required

services:
  - docker

before-insall:
  - docker build -t testcontainer -f Dockerfile.dev .

script:
  - docker run testcontainer npm run test -- --coverage #-- --coverage added to exit after the tests are run
