#Request root permissions to the TravisCI runtime environment
sudo: required
#Tell TravisCI that we're using docker to run our tests
services:
    - docker
#Build our test Docker container
before_install:
  - docker build -t dockerreact -f Dockerfile.dev .

#Run our test Docker container
script:
  - docker run dockerreact

#Build our deployment container
before_deploy:
  - docker build -t dockerreact .

#Run our deployment container via shell script if commiting to the master branch
# deploy:
#   skip_cleanup: true
#   provider: script
#   script: bash ./scripts/deploy.sh
#   on:
#     branch: master

deploy:
  provider: elasticbeanstalk #predefined can be digitalocean, azure etc
  region: us-east-2
  app: dockerreact
  env: DockerReactenv
  # go to services and search s3 to get the bucket name
  bucket_name: elasticbeanstalk-us-east-2-387642852659
  # by default the folder might be empty so better use appname as bucket_path
  bucket_path: dockerreact
  on:
    branch: master # this means only deploy if there is change in the master branch
    # now we need to create a user to allow travis to deploy to aws search for Iam and then create a user like docker-react-travis-ci
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: 
    secure: $AWS_SECRET_ACCESS_KEY 